- dbcrossbarlib/src/drivers/postgres_shared/create_table_sql.rustpeg
sometimes you want `CREATE UNLOGGED TABLE`
```
Error: error parsing Postgres `CREATE TABLE`
caused by: error at 1:8: expected `TABLE`
```
> support unlogged tables

- dbcrossbar/src/cmd/cp.rs
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/src/drivers/bigquery/local_data.rs
- dbcrossbarlib/src/drivers/bigquery/mod.rs
- dbcrossbarlib/src/drivers/bigquery/write_local_data.rs
- dbcrossbarlib/src/drivers/bigquery/write_remote_data.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table_name.rs
- dbcrossbarlib/src/drivers/gs/mod.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
- dbcrossbarlib/src/locator.rs
You can now pass `--temporary=bigquery:proj:dataset`, and that dataset
will be used for storing temporary tables. This makes it possible to set
automatic expiration and it makes it possible to only put "real" tables
inside the final destination dataset.
> Allow overriding BigQuery temp dataset name

- README.md
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/src/csv_stream.rs
- dbcrossbarlib/src/drivers/csv/mod.rs
- dbcrossbarlib/src/drivers/gs/local_data.rs
- dbcrossbarlib/src/drivers/mod.rs
- dbcrossbarlib/src/drivers/s3/local_data.rs
- dbcrossbarlib/src/drivers/s3/mod.rs
- dbcrossbarlib/src/drivers/s3/prepare_as_destination.rs
- dbcrossbarlib/src/drivers/s3/write_local_data.rs
- dbcrossbarlib/src/locator.rs
This shells out to `aws s3 ls`, which means that we can't handle buckets of 1,000+ files correctly. But it accomplishes the basics.
@seamusabshere I'm going to merge this immediately, but I think it would be an excellent idea to review it anyway, because this shows how to implement an entire `dbcrossbar` driver from scratch by wrapping a CLI tool, and somebody but me should see how that works. Skill transfer is important!
> s3: Implement basic S3 driver

- Cargo.lock
- dbcrossbar/src/cmd/cp.rs
- dbcrossbar/src/cmd/mod.rs
- dbcrossbar/src/main.rs
- dbcrossbarlib/src/drivers/bigquery/local_data.rs
- dbcrossbarlib/src/drivers/bigquery/mod.rs
- dbcrossbarlib/src/drivers/bigquery/write_local_data.rs
- dbcrossbarlib/src/drivers/csv/mod.rs
- dbcrossbarlib/src/drivers/gs/local_data.rs
- dbcrossbarlib/src/drivers/gs/mod.rs
- dbcrossbarlib/src/drivers/gs/write_local_data.rs
- dbcrossbarlib/src/drivers/postgres/mod.rs
- dbcrossbarlib/src/drivers/postgres/write_local_data.rs
- dbcrossbarlib/src/drivers/s3/local_data.rs
- dbcrossbarlib/src/drivers/s3/mod.rs
- dbcrossbarlib/src/drivers/s3/write_local_data.rs
- dbcrossbarlib/src/lib.rs
- dbcrossbarlib/src/locator.rs
- dbcrossbarlib/src/tokio_glue.rs
Our core future type is `BoxFuture<T>`, which is currently a
`tokio`-compatible future. This patch converts it to a
`std::future::Future` by removing that wrapper. This involves a
converting a lot of `.boxed().compat()` to `.boxed()`, and inserting the
`.compat()` calls in other places.
This means that we're getting ever-closer to a world where we use
`std::future::Future` everywhere. We're just waiting for `tokio` and the
surrounding ecosystem to make the jump, which may take a while. And for
`.await` to stablize.
> Remove `Compat` wrapper from `BoxFuture<T>`

- Cargo.lock
- dbcrossbar/Cargo.toml
- dbcrossbar/src/cmd/mod.rs
- dbcrossbar/src/logging.rs
- dbcrossbar/src/main.rs
We now support the following structured logging output formats:
- `--log-format=indented`: Pretty, colorized, indented logs, suitable for easy visual scanning.
- `--log-format=flat`: Flat, un-colorized logs, suitable for textual log databases that centralize logs for multiple applications and servers.
- `--log-format=json`: Pure JSON logs, for structured logging systems.
We also add a `--log-extra=key=value`, which allows injecting one or more extra key-value pairs into our logs.
Passing `--log-format=json --log-extra=batch_id=123abc` yields single-line JSON log records that look like:
{
"msg": "...log message here...",
"level": "DEBG",
"ts": "2019-07-24T03:22:21.278078276-04:00",
"batch_id": "123abc",
"ver": "0.2.0-alpha.6",
"app": "dbcrossbar"
}
The `msg`, `level` and `ts` fields are …
> Add `--log-format=json` option (also `flat`)

- dbcrossbar/fixtures/upsert.sql
- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
It turns out that upsert and `NULL` do not play nicely
together. BigQuery joins support neither `IS NOT DISTINCT FROM` nor
compound tests using `IS NOT NULL`. So the best decision here is to only
allow joins on columns which are known to be `REQUIRED` (which maps to
`NOT NULL` columns using SQL table definitions).
> BigQuery: Only allow upsert on REQUIRED columns (fixes #43)

- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
This is a very limited fix to a common problem. It's a one-way fix, in the sense that once it "fixes" dashes there's no way to get them back.
> Replace dashes with underscores when copying to BigQuery - fixes #50

- dbcrossbarlib/src/drivers/bigquery/write_remote_data.rs
- dbcrossbarlib/src/drivers/bigquery_shared/mod.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
When appending, we should do `--append_table` not `--noreplace`
Tested manually.
> Pass correct flag to append to BigQuery (fixes #36)

- Cargo.lock
- dbcrossbar/Cargo.toml
- dbcrossbar/src/cmd/cp.rs
- dbcrossbarlib/src/concat.rs
- dbcrossbarlib/src/lib.rs
- dbcrossbarlib/src/rechunk.rs
This allows controlling the approximate size of the individual CSV data
streams manipulated by `dbcrossbar`. We implement this by merging all
out input streams into a single `CsvStream`, then breaking it up again
into multiple `CsvStream` objects of approximately the requested size.
A couple of tricks were involved:
- The `CountingWriter` counts are not very accurate because of buffering
in `csv::Writer`. We can adjust the buffering but it won't get us
exact counts.
- We don't want to send a newly-created `CsvStream` to
`csv_streams_sender` until we know that it will contain at least one
line.
This involved some fairly fiddly async+sync Rust because of the nature
of combining and re-splitting multiple async streams using a sync `csv`
library. Many thanks to @n1ywb and @fwallacevt for …
> Add `--stream-size` parameter

- Cargo.lock
- dbcrossbar/fixtures/tricky_column_names.csv
- dbcrossbar/fixtures/tricky_column_names.sql
- dbcrossbar/fixtures/tricky_column_names_expected.csv
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
- dbcrossbarlib/src/drivers/postgres_shared/mod.rs
- dbcrossbarlib/src/lib.rs
- dbcrossbarlib/src/uniquifier.rs
We now support column names like:
- `column 1.2`
- `First Name`
- `First name`
...all in the same database.
For BigQuery, this requires us to transform portable column names into
legal BigQuery column names, and append numbers to them to prevent name
clashes.
For PostgreSQL, this requires allowing column names with periods, like
"column 1.2", in the PostgreSQL driver.
Written with @seamusabshere.
> Support strange column names

- Cargo.lock
- dbcrossbar/src/cmd/conv.rs
- dbcrossbar/src/cmd/count.rs
- dbcrossbar/src/cmd/mod.rs
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/args.rs
- dbcrossbarlib/src/drivers/bigml/mod.rs
- dbcrossbarlib/src/drivers/bigquery/count.rs
- dbcrossbarlib/src/drivers/bigquery/mod.rs
- dbcrossbarlib/src/drivers/bigquery/write_remote_data.rs
- dbcrossbarlib/src/drivers/bigquery_schema/mod.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
- dbcrossbarlib/src/drivers/csv/mod.rs
- dbcrossbarlib/src/drivers/dbcrossbar_schema/mod.rs
- dbcrossbarlib/src/drivers/gs/mod.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
- dbcrossbarlib/src/drivers/postgres/count.rs
- dbcrossbarlib/src/drivers/postgres/mod.rs
- dbcrossbarlib/src/drivers/postgres_shared/table.rs
- dbcrossbarlib/src/drivers/postgres_sql/mod.rs
- dbcrossbarlib/src/drivers/redshift/mod.rs
- dbcrossbarlib/src/drivers/s3/mod.rs
- dbcrossbarlib/src/if_exists.rs
- dbcrossbarlib/src/lib.rs
- dbcrossbarlib/src/locator.rs
This can be used to count the rows associated with either a BigQuery or PostgreSQL locator. (In theory, we could add a portable fallback which downloaded data, converted it to CSV, and counted the rows manually, but we don't have that yet. And it would be slower, anyways.)
We also convert from the `bitflags` crate to the less error-prone `enumset` crate that we've had good results with elsewhere. `bitflags` mostly useful when you need C-level compatibility or when you're using an embedded system.
> Add a `dbcrossbar count` subcommand

- dbcrossbar/src/cmd/count.rs
- dbcrossbar/src/cmd/cp.rs
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/src/args.rs
- dbcrossbarlib/src/drivers/bigquery/write_local_data.rs
- dbcrossbarlib/src/drivers/redshift/write_local_data.rs
This will be ignored in certain situations, and it may require an
unreasonable amount of RAM to work with GCloud sources, because copying
from GCloud using the Google CLI tools can use gigabytes of RAM.
> Add a `--max-streams` flag to control max concurrency

- Cargo.lock
- README.md
- dbcrossbar/fixtures/more_pg_types.csv
- dbcrossbar/fixtures/more_pg_types.sql
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/driver_args.rs
- dbcrossbarlib/src/drivers/bigml/write_local_data.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table_name.rs
- dbcrossbarlib/src/drivers/postgres_shared/catalog.rs
- dbcrossbarlib/src/drivers/postgres_shared/create_table_sql.rustpeg
Fixes for a bunch of miscellaneous issues found by @seamusabshere, and add support for tags on `bigml` destinations using `--to-arg=tags[]=bigml-tag-name`.
- Update semver-compatible dependencies, etc.
- bigquery: Quote each part of table name (fixes #79)
- postgres: Support `citext` columns (fixes #81)
- bigml: Support tagging source & datasets (fixes #82)
If you'd prefer, you can review this patch by patch; they should all have comments and stand alone.
> Assorted fixes

- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
Historically, we have allows databases some flexibility in how they
exported Boolean values. PostgreSQL preferred "t"/"f", but BigQuery used
"true"/"false". This was generally safe because most databases have
smart boolean parsing.
But BigML CSV import maps booleans to CATEGORICAL values, which are
strings that must match exactly. So we need to standardize booleans on
t/f everywhere.
This is a "quick fix" patch that relies on existing test cases to make
sure that everything works. We will also need to add _new_ test cases to
ensure standardized representations of as many values as possible, and
strictly document our interchange CSV format. But that can wait.
> bigquery: Export booleans as "t"/"f"

- Cargo.lock
- dbcrossbar/fixtures/bigquery_schema.json
- dbcrossbar/fixtures/bigquery_schema_converted.sql
- dbcrossbar/tests/tests.rs
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/drivers/bigquery/schema.rs
- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
- dbcrossbarlib/src/drivers/bigquery_shared/data_type.rs
- dbcrossbarlib/src/drivers/bigquery_shared/data_type.rustpeg
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
This PR adds support for `RECORD` type columns in BigQuery, which are essentially columns of type `STRUCT<...>`. But they appear in the BigQuery JSON schemas in an inconvenient way, so we have to go out of our way to handle them.
Note that we convert both `RECORD` and `REPEATED RECORD` fields into JSON, which means that (to put in PostgreSQL terms), we serialize `ARRAY<STRUCT<...>>` as `jsonb` containing a JSON array, and not as `jsonb[]`. This was done because @seamusabshere argued that nobody ever wants to see `jsonb[]`, but it involved some slightly non-orthogonal code in the BigQuery driver.
More and more pressure is building is building to implement a "shortcut" system that can handle more data representations than just CSV, but that involves some real thinking before we go there.
> Support exporting BigQuery `RECORD` columns as JSON

- dbcrossbarlib/src/clouds/gcloud/bigquery.rs
- dbcrossbarlib/src/clouds/gcloud/mod.rs
- dbcrossbarlib/src/clouds/gcloud/storage.rs
- dbcrossbarlib/src/clouds/mod.rs
- dbcrossbarlib/src/drivers/bigquery/count.rs
- dbcrossbarlib/src/drivers/bigquery/write_remote_data.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
- dbcrossbarlib/src/drivers/gs/local_data.rs
- dbcrossbarlib/src/drivers/gs/prepare_as_destination.rs
- dbcrossbarlib/src/drivers/gs/write_local_data.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
- dbcrossbarlib/src/lib.rs
- dbcrossbarlib/src/rechunk.rs
This is the first part of the work on fixing `--stream-size` to behave better when passed many 40 MB CSV files from BigQuery. It includes:
1. A performance optimization in the `--stream-size` CSV reading code.
2. A refactoring which isolates `bq` and `gsutil` from the rest of the code, so that we can someday replace them.
I'm proposing this PR now, because (2) is also needed for fixing https://github.com/faradayio/dbcrossbar/issues/45.
> Encapsulate `bq` and `gsutil` & speed up `--stream-size`

- README.md
- dbcrossbar/tests/cli/cp/bigquery.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery.rs
- dbcrossbarlib/src/drivers/bigquery/write_remote_data.rs
- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
For imports that required a custom SELECT to fix up the data, we used to
lose `NOT NULL` declarations on the columns, because we used `SELECT` to
create the destination table, and there's no way to represent `NOT
NULL`.
This patch rips all that out and replaces it with multi-statement SQL
scripts that include explicit `CREATE TABLE` statements.
This cleans up a bunch of dodgy logic in `bigquery::write_remote_data`
that I didn't really like. The whole business with `if_exists` and
upserts is now less hackish.
> bigquery: Honor `NOT NULL` on import (fixes #45)

- dbcrossbar/fixtures/exact_output.csv
- dbcrossbar/fixtures/exact_output.sql
- dbcrossbar/fixtures/upsert.sql
- dbcrossbar/fixtures/upsert_1.csv
- dbcrossbar/fixtures/upsert_2.csv
- dbcrossbar/fixtures/upsert_result.csv
- dbcrossbar/tests/cli/cp/bigquery.rs
- dbcrossbarlib/src/drivers/bigquery_shared/column.rs
- dbcrossbarlib/src/drivers/bigquery_shared/column_name.rs
- dbcrossbarlib/src/drivers/bigquery_shared/data_type.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table.rs
We removed quoting on BigQuery column in 0.3.0, because we knew they
were well-behaved identifiers. But I forgot about names like "group" and
"select".
This patch prints BigQuery column names in quoted format again.
> Requote BigQuery columns

- Cargo.lock
- README.md
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/clouds/gcloud/client.rs
- dbcrossbarlib/src/clouds/gcloud/storage/download_file.rs
- dbcrossbarlib/src/clouds/gcloud/storage/ls.rs
- dbcrossbarlib/src/clouds/gcloud/storage/mod.rs
- dbcrossbarlib/src/clouds/gcloud/storage/rmdir.rs
- dbcrossbarlib/src/drivers/bigquery_shared/table_name.rs
- dbcrossbarlib/src/drivers/gs/local_data.rs
- deny.toml
This PR includes two improvements:
1. A correctness fix to the `ls` code.
2. A major performance and backpressure fix to `download_file` which basically amounts to a rewrite.
We should probably devote some more effort to batching `rm` and to making `upload_file` chunked, too. But this is a very good start.
This leaves only a few items on https://github.com/dbcrossbar/dbcrossbar/issues/112 that are blocking a useful 0.4.0-alpha.1 release.
> Google Cloud Storage fixes

- Cargo.lock
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/clouds/gcloud/auth.rs
- dbcrossbarlib/src/credentials.rs
- dbcrossbarlib/src/lib.rs
- guide/src/bigquery.md
- guide/src/gs.md
- guide/src/installing.md
This PR includes two important missing pieces that we need for an alpha release:
- Support for `~/.config/dbcrossbar/gcloud_client_secret.json`.
- Documentation updates for the new native Rust drivers, including the authentication changes.
Once this is merged, I'll need an hour or so at some point to actually prepare an alpha release.
> Prepare for v0.4.0-alpha.1

- dbcrossbarlib/src/clouds/gcloud/auth.rs
- dbcrossbarlib/src/clouds/gcloud/client.rs
We need this directory to store GCloud tokens, and `yup_oauth2` doesn't
create it. We also improve the error message if `yup_oauth2` fails.
> gcloud: Automatically create `~/.local/share`

- Cargo.lock
- dbcrossbar/fixtures/dbcrossbar_ts/shapes.json
- dbcrossbar/fixtures/dbcrossbar_ts/shapes.ts
- dbcrossbar/tests/cli/conv.rs
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/drivers/dbcrossbar_schema/mod.rs
- dbcrossbarlib/src/drivers/dbcrossbar_ts/ast.rs
- dbcrossbarlib/src/drivers/dbcrossbar_ts/mod.rs
- dbcrossbarlib/src/drivers/dbcrossbar_ts/shopify.ts
- dbcrossbarlib/src/drivers/mod.rs
- dbcrossbarlib/src/lib.rs
- dbcrossbarlib/src/locator.rs
- dbcrossbarlib/src/parse_error.rs
We need some way to specify schemas containing complex, nested
structs. This will be particularly useful for BigQuery and for
importing structured JSON data.
You should now be able to write:
dbcrossbar conv \
'dbcrossbar-ts:schema.ts#Type' \
dbcrossbar-schema:type.json
This is implemented using another `peg` parser, which parses
TypeScript using a Parser Expression Grammar (PEG). This is sort of
like a hierarchical regular expression with names rules.
We devote a substantial amount of effort to providing excellent error
messages that highlight errors directly in the TypeScript source.
We support basic types including `interface`, `type` (for aliases),
arrays, primitive types, and `field: ty | null` syntax. We require
semi-colons and commas everywhere they can go, though we may
eventually …
> dbcrossbar-ts: Specify schemas with a subset of TypeScript

- dbcrossbar/fixtures/more_bq_types.csv
- dbcrossbar/fixtures/more_bq_types.sql
- dbcrossbar/fixtures/shopify.ts
- dbcrossbar/fixtures/structs/struct-data-type-after-bq.json
- dbcrossbar/fixtures/structs/struct-data-type.json
- dbcrossbar/fixtures/structs/struct.json
- dbcrossbar/tests/cli/cp/bigquery.rs
- dbcrossbarlib/src/drivers/bigquery_shared/import_udf.rs
- dbcrossbarlib/src/drivers/dbcrossbar_ts/ast.rs
We make sure that exact decimal numbers work with BigQuery and with
`dbcrossbar-ts`. The latter is a little magic.
> Improve decimal handling

- dbcrossbar/fixtures/shopify.ts
- dbcrossbarlib/src/drivers/dbcrossbar_ts/ast.rs
I made another pass through the Shopify docs, and tried to improve the schema. Major highlights include:
- We now use `Date` for dates, which will map to a BigQuery `TIMESTAMP`.
- It's now possible to write `type decimal = number | string`, because Shopify allows both `number` and `string` values for currency in several important places.
- We now use `int64` for things which look like integer values, which should prevent BigQuery from formatting `id` fields in scientific notation.
- `Address` (on `Order`) and `CustomerAddress` have been split, because they're not actually the same thing.
- Several other minor issues have been cleaned up.
> Improve `shopify.ts`

- dbcrossbar/tests/cli/cp/bigquery.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery/extract.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery/jobs.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery/load.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery/mod.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery/queries.rs
- dbcrossbarlib/src/driver_args.rs
- dbcrossbarlib/src/drivers/bigquery/count.rs
- dbcrossbarlib/src/drivers/bigquery/mod.rs
- dbcrossbarlib/src/drivers/bigquery/write_remote_data.rs
- dbcrossbarlib/src/drivers/bigquery_shared/driver_args.rs
- dbcrossbarlib/src/drivers/bigquery_shared/mod.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
- dbcrossbarlib/src/drivers/redshift/mod.rs
- guide/src/bigquery.md
Google Cloud allows specifying optional labels on many kinds of resources, in order to help keep track of costs. This implements basic labels for BigQuery jobs, but nothing else. Please see the individual commit messages for details, and see the change to `bigquery.md` for documentation about how to specify labels.
This implements a stable API that we can live with, so we don't need to hide it behind `--enable-unstable`.
- We can, in theory, apply labels to all of the following. Which do we need urgently?
- **Done:** BigQuery jobs, including import, export and query. This may also apply to tables created automatically as part of a job; I need to look into that.
- **TODO:** BigQuery tables. But we need to be careful here, because just because a table was _created_ by a specific dbcrossbar …
> bigquery: Optionally specifiy job labels (fixes #123)

- Cargo.lock
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/clouds/gcloud/bigquery/jobs.rs
- dbcrossbarlib/src/clouds/gcloud/client.rs
- dbcrossbarlib/src/clouds/gcloud/crc32c_stream.rs
- dbcrossbarlib/src/clouds/gcloud/mod.rs
- dbcrossbarlib/src/clouds/gcloud/storage/download_file.rs
- dbcrossbarlib/src/clouds/gcloud/storage/mod.rs
- dbcrossbarlib/src/clouds/gcloud/storage/upload_file.rs
We add support for the `ifGenerationMatch` parameter across our Google
Cloud Storage code. This allows us to (1) make sure nobody has created
a file behind our back mid-operation, and (2) make sure that nobody
has replaced a file we're using.
We also check CRC32C checksums on upload. Ideally, we'd do this on
download, too, but we haven't implemented that.
This code was part of an attempt to add support for streaming
composite uploads to Google Cloud Storage, but this involves several
annoying sub-problems that I don't want to get into before the 0.4.0
release.
There's some more composite-related code that isn't included in this
PR. (I may check it into a WIP branch.) This explains why a few APIs
appear to have been generalized slightly for no obvious reason.
> gs: Verify generations & CRC32C checksums

- dbcrossbarlib/src/clouds/aws/s3/mod.rs
- dbcrossbarlib/src/credentials.rs
- guide/src/s3.md
`aws s3` will actually default this in some (many? all?) cases, but I
couldn't find any documentation on the exact rules. So I'm going to make
this mandatory for now to avoid relying on unspecified behavior.
> s3: Require AWS_DEFAULT_REGION

- dbcrossbar/tests/cli/cp/bigquery.rs
- dbcrossbarlib/src/drivers/shopify/local_data.rs
I'm hearing reports of transient errors when downloading from Shopify. If we add retries that might help.
> shopify: Allow several retries

- dbcrossbarlib/src/drivers/postgres_shared/catalog.rs
```
StandardError dbcrossbar cp failed pid 21 exit 1
app: dbcrossbar
ver: 0.4.2-beta.6
Error: error reading schema from postgres://xxx
caused by: unknown array element "_varchar"
```
> postgres: support array of varchar

- dbcrossbar/tests/cli/cp/redshift.rs
- dbcrossbarlib/src/drivers/redshift/mod.rs
- dbcrossbarlib/src/drivers/redshift/write_remote_data.rs
- dbcrossbarlib/src/drivers/s3/write_remote_data.rs
- guide/src/redshift.md
Users who are participating in the RedShift partner program need to be
able to generate specially-formatted comments in SQL queries.
> redshift: Add "partner" comment support

- dbcrossbarlib/src/clouds/gcloud/bigquery/jobs.rs
- dbcrossbarlib/src/drivers/bigml/data_type.rs
- dbcrossbarlib/src/drivers/bigquery_shared/column_name.rs
- guide/src/bigml.md
String enumerations should always map to BigML categorical values.
Co-authored-by: Tom Caruso <tom@tcaruso.com>
> bigml: Fix `one-of` to map to categorical value

- CHANGELOG.md
- dbcrossbarlib/src/clouds/gcloud/bigquery/mod.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
This appears to be a transient error caused by an authorization race
condition in Google Cloud.
Fixes #181.
> bigquery: Retry `extract` after `accessDenied`

- CHANGELOG.md
- dbcrossbarlib/src/clouds/gcloud/client.rs
- dbcrossbarlib/src/clouds/gcloud/storage/mod.rs
- dbcrossbarlib/src/clouds/gcloud/storage/rm_r.rs
- dbcrossbarlib/src/drivers/gs/write_remote_data.rs
Another attempt at dealing with the mysterious "access denied" errors
from Google Cloud Storage that appear transiently, but only for writes.
Fixes #181. Again. Maybe.
> gs: Retry deletes which fail with 403

- Cargo.lock
- dbcrossbar/tests/cli/cp/bigquery.rs
- dbcrossbar/tests/cli/cp/bigquery_test_fixture.rs
- dbcrossbar/tests/cli/cp/mod.rs
- dbcrossbarlib/Cargo.toml
- dbcrossbarlib/src/clouds/gcloud/bigquery/mod.rs
- dbcrossbarlib/src/clouds/gcloud/bigquery/tables.rs
- dbcrossbarlib/src/clouds/gcloud/client.rs
- dbcrossbarlib/src/clouds/gcloud/storage/rm_r.rs
- dbcrossbarlib/src/csv_stream.rs
- dbcrossbarlib/src/drivers/bigquery_shared/mod.rs
- dbcrossbarlib/src/drivers/bigquery_shared/write_bigquery_sql.rs
- dbcrossbarlib/src/drivers/bigquery_test_fixture/mod.rs
- dbcrossbarlib/src/drivers/mod.rs
- dbcrossbarlib/src/from_csv_cell.rs
- dbcrossbarlib/src/from_json_value.rs
- dbcrossbarlib/src/locator.rs
- guide/src/bigquery.md
- guide/src/gs.md
Creating small input tables on BigQuery for tests takes around 15-30
seconds. This is expected when working with typically large tables.
But when writing unit tests for programs that use BigQuery, we need to create
many small tables from fixture data. Paying 15-30 seconds each is
terrible.
Dave discovered a clever hack: For small read-only tables, we can load
data inline in VIEWs. This can be done in less than 0.7 seconds, which
is much nicer.
Dave and I worked together to port his Python implementation into
dbcrossbar and to extend it to handle many more types.
Limitations: We do not support STRUCT types yet.
If an input table is too big, we try to fail over to uploading using
the regular BigQuery driver.
Open questions:
- Should we materialize all views?
- Should we make the cutoff …
> Add new `bigquery-test-fixture` schema

- dbcrossbarlib/src/drivers/bigquery_test_fixture/mod.rs
Above this limit the driver will fall back to the regular bigquery
driver.  In some cases the limit may be too high since we do not
check the final view size.
> Increasing the max CSV size for bigquery-test-fixture

- guide/src/schema.md
the dbcrossbar schema docs misspell the data type for geojson.
> typo in docs: geojson -> geo_json

- dbcrossbar/src/drivers/postgres/csv_to_binary/mod.rs
- dbcrossbar/src/drivers/postgres_shared/data_type.rs
- dbcrossbar/src/drivers/redshift/mod.rs
- dbcrossbar/src/drivers/redshift/write_remote_data.rs
- dbcrossbar/tests/cli/cp/redshift.rs
In RedShift, TEXT is an alias for VARCHAR(255). We
want VARCHAR(MAX) instead.
But since RedShift only works because it
piggybacks off of our better-supported PostgreSQL
driver, we need to thread the VARCHAR(MAX) type
through the postgres_shared module, and error out
if it shows up in PostgreSQL-specific code.
This has not yet been tested against RedShift,
because I don't have access to an instance right
now. But once a test system is available, this
should get us close.
> redshift: Try to use VARCHAR(MAX)

- dbcrossbar/src/clouds/gcloud/bigquery/jobs.rs
- dbcrossbar/src/clouds/gcloud/bigquery/tables.rs
- dbcrossbar/src/clouds/gcloud/client.rs
Bigquery fixture uploads fail relatively frequently with 503 errors from Google, but could be safely retried.
This PR adds a retry mechanism for POST requests that fail with a 503.
> add retry helper for POST requests for 503s
